# Config file for air (hot reloading for Go)

root = "."
tmp_dir = "tmp"

[build]
# Array of commands to run before each build
pre_cmd = []
# Command to build the binary
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
# Binary file path
bin = "tmp/main"
# Array of commands to run after each build
post_cmd = []
# Watch the listed extensions
include_ext = ["go", "tpl", "tmpl", "html"]
# Exclude directories
exclude_dir = ["assets", "tmp", "vendor", "web"]
# Exclude files
exclude_file = []
# Kill the process before starting a new one
delay = 1000
# Whether to delete temporary directory on exit
clean_on_exit = true

[color]
# Color for main build success
main = "green"
# Color for watcher success
watcher = "cyan"
# Color for build success
build = "yellow"
# Color for runner success
runner = "green"

[log]
# Show log timestamps
time = true

[misc]
# Whether to clean screen before next run
clean_on_exit = true 